<?php
declare(strict_types=1);

namespace Apple\Enum;

enum NotificationType: string
{
    case CONSUMPTION_REQUEST = 'CONSUMPTION_REQUEST'; // not in use
    case DID_CHANGE_RENEWAL_PREF = 'DID_CHANGE_RENEWAL_PREF';
    case DID_CHANGE_RENEWAL_STATUS = 'DID_CHANGE_RENEWAL_STATUS';
    case DID_FAIL_TO_RENEW = 'DID_FAIL_TO_RENEW';
    case DID_RENEW = 'DID_RENEW';
    case EXPIRED = 'EXPIRED';
    case GRACE_PERIOD_EXPIRED = 'GRACE_PERIOD_EXPIRED';
    case OFFER_REDEEMED = 'OFFER_REDEEMED';
    case PRICE_INCREASE = 'PRICE_INCREASE';
    case REFUND = 'REFUND';
    case REFUND_DECLINED = 'REFUND_DECLINED';
    case RENEWAL_EXTENDED = 'RENEWAL_EXTENDED';
    case REVOKE = 'REVOKE';
    case SUBSCRIBED = 'SUBSCRIBED';
    case TEST = 'TEST';
}