framework:
    cache:
        prefix_seed: wtorsi/in-app-purchases
        default_redis_provider: '%env(REDIS_URL)%'
        app: cache.adapter.redis
        system: cache.adapter.redis
        pools:
            cache.apcu:
                adapter: cache.adapter.apcu
                default_lifetime: 86400

            cache.redis:
                adapter: cache.adapter.redis
                default_lifetime: 86400