framework:
    messenger:
        default_bus: command.bus
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        buses:
            event.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection

        failure_transport: failed

        transports:
            async: '%env(MESSENGER_ASYNC_DSN)%'
            failed: '%env(MESSENGER_FAILED_DSN)%'
